# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from workday_staffing_python_sdk.paths.job_profiles_id.get import GetById
from workday_staffing_python_sdk.paths.job_profiles.get import ListCollection
from workday_staffing_python_sdk.apis.tags.job_profiles_api_raw import JobProfilesApiRaw


class JobProfilesApi(
    GetById,
    ListCollection,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: JobProfilesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = JobProfilesApiRaw(api_client)
