# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from workday_staffing_python_sdk.paths.jobs.get import GetCollectionRaw
from workday_staffing_python_sdk.paths.jobs_id.get import GetJobByIdRaw
from workday_staffing_python_sdk.paths.jobs_id_workspace_subresource_id.get import GetWorkspaceRaw
from workday_staffing_python_sdk.paths.jobs_id_workspace.get import GetWorkspacesRaw


class JobsApiRaw(
    GetCollectionRaw,
    GetJobByIdRaw,
    GetWorkspaceRaw,
    GetWorkspacesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
