# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from workday_staffing_python_sdk.paths.values_job_changes_group_locations.get import AvailableLocationsRaw
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_cost_centers.get import GetAssignmentChangeGroupCostCentersRaw
from workday_staffing_python_sdk.paths.values_job_changes_group_assignment_types.get import GetAssignmentTypesRaw
from workday_staffing_python_sdk.paths.values_job_changes_group_company_insider_types.get import GetCompanyInsiderTypesRaw
from workday_staffing_python_sdk.paths.values_job_changes_group_contingent_worker_types.get import GetContingentWorkerTypesRaw
from workday_staffing_python_sdk.paths.values_job_changes_group_currencies.get import GetCurrencyInstancesRaw
from workday_staffing_python_sdk.paths.values_job_changes_group_employee_types.get import GetEmployeeTypesRaw
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_gifts.get import GetGiftInstancesRaw
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_grants.get import GetGrantsRaw
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_regions.get import GetInstancesRaw
from workday_staffing_python_sdk.paths.values_job_changes_group_reason.get import GetInstances0Raw
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_customs.get import GetInstances1Raw
from workday_staffing_python_sdk.paths.values_job_changes_group_templates.get import GetInstances10Raw
from workday_staffing_python_sdk.paths.values_job_changes_group_workers.get import GetInstances11Raw
from workday_staffing_python_sdk.paths.values_job_changes_group_jobs.get import GetInstances12Raw
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_workers.get import GetInstances13Raw
from workday_staffing_python_sdk.paths.values_job_changes_group_work_study_awards.get import GetInstances14Raw
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_positions.get import GetInstances15Raw
from workday_staffing_python_sdk.paths.values_job_changes_group_job_requisitions.get import GetInstances16Raw
from workday_staffing_python_sdk.paths.values_job_changes_group_job_profiles.get import GetInstances17Raw
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_companies.get import GetInstances18Raw
from workday_staffing_python_sdk.paths.values_job_changes_group_job_classifications.get import GetInstances19Raw
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_programs.get import GetInstances2Raw
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_jobs.get import GetInstances3Raw
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_funds.get import GetInstances4Raw
from workday_staffing_python_sdk.paths.values_job_changes_group_workers_compensation_code_overrides.get import GetInstances5Raw
from workday_staffing_python_sdk.paths.values_job_changes_group_work_shifts.get import GetInstances6Raw
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_business_units.get import GetInstances7Raw
from workday_staffing_python_sdk.paths.values_job_changes_group_frequencies.get import GetInstances8Raw
from workday_staffing_python_sdk.paths.values_job_changes_group_pay_rate_types.get import GetInstances9Raw
from workday_staffing_python_sdk.paths.values_job_changes_group_headcount_options.get import GetOptionsRaw
from workday_staffing_python_sdk.paths.values_job_changes_group_proposed_position.get import GetProposedPositionsRaw
from workday_staffing_python_sdk.paths.values_job_changes_group_supervisory_organization.get import GetSupervisoryOrgValuesRaw
from workday_staffing_python_sdk.paths.values_job_changes_group_time_types.get import GetTimeTypesRaw
from workday_staffing_python_sdk.paths.values_job_changes_group_worker_types.get import GetWorkerTypesRaw
from workday_staffing_python_sdk.paths.values_job_changes_group_work_spaces.get import GetWorkspaceInstancesRaw


class PromptValuesApiRaw(
    AvailableLocationsRaw,
    GetAssignmentChangeGroupCostCentersRaw,
    GetAssignmentTypesRaw,
    GetCompanyInsiderTypesRaw,
    GetContingentWorkerTypesRaw,
    GetCurrencyInstancesRaw,
    GetEmployeeTypesRaw,
    GetGiftInstancesRaw,
    GetGrantsRaw,
    GetInstancesRaw,
    GetInstances0Raw,
    GetInstances1Raw,
    GetInstances10Raw,
    GetInstances11Raw,
    GetInstances12Raw,
    GetInstances13Raw,
    GetInstances14Raw,
    GetInstances15Raw,
    GetInstances16Raw,
    GetInstances17Raw,
    GetInstances18Raw,
    GetInstances19Raw,
    GetInstances2Raw,
    GetInstances3Raw,
    GetInstances4Raw,
    GetInstances5Raw,
    GetInstances6Raw,
    GetInstances7Raw,
    GetInstances8Raw,
    GetInstances9Raw,
    GetOptionsRaw,
    GetProposedPositionsRaw,
    GetSupervisoryOrgValuesRaw,
    GetTimeTypesRaw,
    GetWorkerTypesRaw,
    GetWorkspaceInstancesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
