# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from workday_staffing_python_sdk.paths.values_job_changes_group_locations.get import AvailableLocations
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_cost_centers.get import GetAssignmentChangeGroupCostCenters
from workday_staffing_python_sdk.paths.values_job_changes_group_assignment_types.get import GetAssignmentTypes
from workday_staffing_python_sdk.paths.values_job_changes_group_company_insider_types.get import GetCompanyInsiderTypes
from workday_staffing_python_sdk.paths.values_job_changes_group_contingent_worker_types.get import GetContingentWorkerTypes
from workday_staffing_python_sdk.paths.values_job_changes_group_currencies.get import GetCurrencyInstances
from workday_staffing_python_sdk.paths.values_job_changes_group_employee_types.get import GetEmployeeTypes
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_gifts.get import GetGiftInstances
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_grants.get import GetGrants
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_regions.get import GetInstances
from workday_staffing_python_sdk.paths.values_job_changes_group_reason.get import GetInstances0
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_customs.get import GetInstances1
from workday_staffing_python_sdk.paths.values_job_changes_group_templates.get import GetInstances10
from workday_staffing_python_sdk.paths.values_job_changes_group_workers.get import GetInstances11
from workday_staffing_python_sdk.paths.values_job_changes_group_jobs.get import GetInstances12
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_workers.get import GetInstances13
from workday_staffing_python_sdk.paths.values_job_changes_group_work_study_awards.get import GetInstances14
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_positions.get import GetInstances15
from workday_staffing_python_sdk.paths.values_job_changes_group_job_requisitions.get import GetInstances16
from workday_staffing_python_sdk.paths.values_job_changes_group_job_profiles.get import GetInstances17
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_companies.get import GetInstances18
from workday_staffing_python_sdk.paths.values_job_changes_group_job_classifications.get import GetInstances19
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_programs.get import GetInstances2
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_jobs.get import GetInstances3
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_funds.get import GetInstances4
from workday_staffing_python_sdk.paths.values_job_changes_group_workers_compensation_code_overrides.get import GetInstances5
from workday_staffing_python_sdk.paths.values_job_changes_group_work_shifts.get import GetInstances6
from workday_staffing_python_sdk.paths.values_organization_assignment_changes_group_business_units.get import GetInstances7
from workday_staffing_python_sdk.paths.values_job_changes_group_frequencies.get import GetInstances8
from workday_staffing_python_sdk.paths.values_job_changes_group_pay_rate_types.get import GetInstances9
from workday_staffing_python_sdk.paths.values_job_changes_group_headcount_options.get import GetOptions
from workday_staffing_python_sdk.paths.values_job_changes_group_proposed_position.get import GetProposedPositions
from workday_staffing_python_sdk.paths.values_job_changes_group_supervisory_organization.get import GetSupervisoryOrgValues
from workday_staffing_python_sdk.paths.values_job_changes_group_time_types.get import GetTimeTypes
from workday_staffing_python_sdk.paths.values_job_changes_group_worker_types.get import GetWorkerTypes
from workday_staffing_python_sdk.paths.values_job_changes_group_work_spaces.get import GetWorkspaceInstances
from workday_staffing_python_sdk.apis.tags.prompt_values_api_raw import PromptValuesApiRaw


class PromptValuesApi(
    AvailableLocations,
    GetAssignmentChangeGroupCostCenters,
    GetAssignmentTypes,
    GetCompanyInsiderTypes,
    GetContingentWorkerTypes,
    GetCurrencyInstances,
    GetEmployeeTypes,
    GetGiftInstances,
    GetGrants,
    GetInstances,
    GetInstances0,
    GetInstances1,
    GetInstances10,
    GetInstances11,
    GetInstances12,
    GetInstances13,
    GetInstances14,
    GetInstances15,
    GetInstances16,
    GetInstances17,
    GetInstances18,
    GetInstances19,
    GetInstances2,
    GetInstances3,
    GetInstances4,
    GetInstances5,
    GetInstances6,
    GetInstances7,
    GetInstances8,
    GetInstances9,
    GetOptions,
    GetProposedPositions,
    GetSupervisoryOrgValues,
    GetTimeTypes,
    GetWorkerTypes,
    GetWorkspaceInstances,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PromptValuesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PromptValuesApiRaw(api_client)
