# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from workday_staffing_python_sdk.paths.supervisory_organizations.get import GetByIdRaw
from workday_staffing_python_sdk.paths.supervisory_organizations_id.get import GetInstanceRaw
from workday_staffing_python_sdk.paths.supervisory_organizations_id_members_subresource_id.get import GetMemberRaw
from workday_staffing_python_sdk.paths.supervisory_organizations_id_members.get import GetMembersRaw
from workday_staffing_python_sdk.paths.supervisory_organizations_id_org_chart.get import GetOrgChartRaw
from workday_staffing_python_sdk.paths.supervisory_organizations_id_org_chart_subresource_id.get import GetOrgChart0Raw


class SupervisoryOrganizationsApiRaw(
    GetByIdRaw,
    GetInstanceRaw,
    GetMemberRaw,
    GetMembersRaw,
    GetOrgChartRaw,
    GetOrgChart0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
