# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from workday_staffing_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from workday_staffing_python_sdk.api_response import AsyncGeneratorResponse
from workday_staffing_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from workday_staffing_python_sdk import schemas  # noqa: F401

from workday_staffing_python_sdk.model.mass_action_header_cf97466f96d910002bd32afbf0000001 import MassActionHeaderCf97466f96d910002bd32afbf0000001 as MassActionHeaderCf97466f96d910002bd32afbf0000001Schema
from workday_staffing_python_sdk.model.validationerrormodelreference import VALIDATIONERRORMODELREFERENCE as VALIDATIONERRORMODELREFERENCESchema
from workday_staffing_python_sdk.model.errormodelreference import ERRORMODELREFERENCE as ERRORMODELREFERENCESchema
from workday_staffing_python_sdk.model.organization_assignment_changes_post_position_cf97466f96d9100029bffcf91c120000 import OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000 as OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000Schema
from workday_staffing_python_sdk.model.mass_action_worksheet31485c9a93c0100007276cf4e5640000 import MassActionWorksheet31485c9a93c0100007276cf4e5640000 as MassActionWorksheet31485c9a93c0100007276cf4e5640000Schema
from workday_staffing_python_sdk.model.position_cf97466f96d9100029bffcf91c120001 import PositionCf97466f96d9100029bffcf91c120001 as PositionCf97466f96d9100029bffcf91c120001Schema

from workday_staffing_python_sdk.type.errormodelreference import ERRORMODELREFERENCE
from workday_staffing_python_sdk.type.validationerrormodelreference import VALIDATIONERRORMODELREFERENCE
from workday_staffing_python_sdk.type.mass_action_worksheet31485c9a93c0100007276cf4e5640000 import MassActionWorksheet31485c9a93c0100007276cf4e5640000
from workday_staffing_python_sdk.type.position_cf97466f96d9100029bffcf91c120001 import PositionCf97466f96d9100029bffcf91c120001
from workday_staffing_python_sdk.type.organization_assignment_changes_post_position_cf97466f96d9100029bffcf91c120000 import OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000
from workday_staffing_python_sdk.type.mass_action_header_cf97466f96d910002bd32afbf0000001 import MassActionHeaderCf97466f96d910002bd32afbf0000001

from ...api_client import Dictionary
from workday_staffing_python_sdk.pydantic.mass_action_header_cf97466f96d910002bd32afbf0000001 import MassActionHeaderCf97466f96d910002bd32afbf0000001 as MassActionHeaderCf97466f96d910002bd32afbf0000001Pydantic
from workday_staffing_python_sdk.pydantic.mass_action_worksheet31485c9a93c0100007276cf4e5640000 import MassActionWorksheet31485c9a93c0100007276cf4e5640000 as MassActionWorksheet31485c9a93c0100007276cf4e5640000Pydantic
from workday_staffing_python_sdk.pydantic.position_cf97466f96d9100029bffcf91c120001 import PositionCf97466f96d9100029bffcf91c120001 as PositionCf97466f96d9100029bffcf91c120001Pydantic
from workday_staffing_python_sdk.pydantic.validationerrormodelreference import VALIDATIONERRORMODELREFERENCE as VALIDATIONERRORMODELREFERENCEPydantic
from workday_staffing_python_sdk.pydantic.organization_assignment_changes_post_position_cf97466f96d9100029bffcf91c120000 import OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000 as OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000Pydantic
from workday_staffing_python_sdk.pydantic.errormodelreference import ERRORMODELREFERENCE as ERRORMODELREFERENCEPydantic

from . import path

# body param
SchemaForRequestBodyApplicationJson = OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000Schema


request_body_organization_assignment_changes_post_position_cf97466f96d9100029bffcf91c120000 = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
SchemaFor201ResponseBodyApplicationJson = OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000Schema


@dataclass
class ApiResponseFor201(api_client.ApiResponse):
    body: OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000


@dataclass
class ApiResponseFor201Async(api_client.AsyncApiResponse):
    body: OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000


_response_for_201 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor201,
    response_cls_async=ApiResponseFor201Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor201ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = VALIDATIONERRORMODELREFERENCESchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
SchemaFor401ResponseBodyApplicationJson = VALIDATIONERRORMODELREFERENCESchema


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor401ResponseBodyApplicationJson),
    },
)
SchemaFor403ResponseBodyApplicationJson = VALIDATIONERRORMODELREFERENCESchema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
    },
)
SchemaFor404ResponseBodyApplicationJson = VALIDATIONERRORMODELREFERENCESchema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
    },
)
SchemaFor0ResponseBodyApplicationJson = ERRORMODELREFERENCESchema


@dataclass
class ApiResponseForDefault(api_client.ApiResponse):
    body: ERRORMODELREFERENCE


@dataclass
class ApiResponseForDefaultAsync(api_client.AsyncApiResponse):
    body: ERRORMODELREFERENCE


_response_for_default = api_client.OpenApiResponse(
    response_cls=ApiResponseForDefault,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor0ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '201': _response_for_201,
    '400': _response_for_400,
    '401': _response_for_401,
    '403': _response_for_403,
    '404': _response_for_404,
    'default': _response_for_default,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _create_change_event_mapped_args(
        self,
        position: typing.Optional[PositionCf97466f96d9100029bffcf91c120001] = None,
        mass_action_worksheet: typing.Optional[MassActionWorksheet31485c9a93c0100007276cf4e5640000] = None,
        mass_action_header: typing.Optional[MassActionHeaderCf97466f96d910002bd32afbf0000001] = None,
        date: typing.Optional[date] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if position is not None:
            _body["position"] = position
        if mass_action_worksheet is not None:
            _body["massActionWorksheet"] = mass_action_worksheet
        if mass_action_header is not None:
            _body["massActionHeader"] = mass_action_header
        if date is not None:
            _body["date"] = date
        if id is not None:
            _body["id"] = id
        if descriptor is not None:
            _body["descriptor"] = descriptor
        args.body = _body
        return args

    async def _acreate_change_event_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Creates a new change organization assignment event for a specific filled or unfilled position.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/organizationAssignmentChanges',
            body=body,
            headers=_headers,
        )
        serialized_data = request_body_organization_assignment_changes_post_position_cf97466f96d9100029bffcf91c120000.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserializationAsync(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _create_change_event_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor201,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Creates a new change organization assignment event for a specific filled or unfilled position.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/organizationAssignmentChanges',
            body=body,
            headers=_headers,
        )
        serialized_data = request_body_organization_assignment_changes_post_position_cf97466f96d9100029bffcf91c120000.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CreateChangeEventRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acreate_change_event(
        self,
        position: typing.Optional[PositionCf97466f96d9100029bffcf91c120001] = None,
        mass_action_worksheet: typing.Optional[MassActionWorksheet31485c9a93c0100007276cf4e5640000] = None,
        mass_action_header: typing.Optional[MassActionHeaderCf97466f96d910002bd32afbf0000001] = None,
        date: typing.Optional[date] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_change_event_mapped_args(
            body=body,
            position=position,
            mass_action_worksheet=mass_action_worksheet,
            mass_action_header=mass_action_header,
            date=date,
            id=id,
            descriptor=descriptor,
        )
        return await self._acreate_change_event_oapg(
            body=args.body,
            **kwargs,
        )
    
    def create_change_event(
        self,
        position: typing.Optional[PositionCf97466f96d9100029bffcf91c120001] = None,
        mass_action_worksheet: typing.Optional[MassActionWorksheet31485c9a93c0100007276cf4e5640000] = None,
        mass_action_header: typing.Optional[MassActionHeaderCf97466f96d910002bd32afbf0000001] = None,
        date: typing.Optional[date] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_change_event_mapped_args(
            body=body,
            position=position,
            mass_action_worksheet=mass_action_worksheet,
            mass_action_header=mass_action_header,
            date=date,
            id=id,
            descriptor=descriptor,
        )
        return self._create_change_event_oapg(
            body=args.body,
        )

class CreateChangeEvent(BaseApi):

    async def acreate_change_event(
        self,
        position: typing.Optional[PositionCf97466f96d9100029bffcf91c120001] = None,
        mass_action_worksheet: typing.Optional[MassActionWorksheet31485c9a93c0100007276cf4e5640000] = None,
        mass_action_header: typing.Optional[MassActionHeaderCf97466f96d910002bd32afbf0000001] = None,
        date: typing.Optional[date] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000Pydantic:
        raw_response = await self.raw.acreate_change_event(
            body=body,
            position=position,
            mass_action_worksheet=mass_action_worksheet,
            mass_action_header=mass_action_header,
            date=date,
            id=id,
            descriptor=descriptor,
            **kwargs,
        )
        if validate:
            return RootModel[OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000Pydantic](raw_response.body).root
        return api_client.construct_model_instance(OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000Pydantic, raw_response.body)
    
    
    def create_change_event(
        self,
        position: typing.Optional[PositionCf97466f96d9100029bffcf91c120001] = None,
        mass_action_worksheet: typing.Optional[MassActionWorksheet31485c9a93c0100007276cf4e5640000] = None,
        mass_action_header: typing.Optional[MassActionHeaderCf97466f96d910002bd32afbf0000001] = None,
        date: typing.Optional[date] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
        validate: bool = False,
    ) -> OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000Pydantic:
        raw_response = self.raw.create_change_event(
            body=body,
            position=position,
            mass_action_worksheet=mass_action_worksheet,
            mass_action_header=mass_action_header,
            date=date,
            id=id,
            descriptor=descriptor,
        )
        if validate:
            return RootModel[OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000Pydantic](raw_response.body).root
        return api_client.construct_model_instance(OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000Pydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        position: typing.Optional[PositionCf97466f96d9100029bffcf91c120001] = None,
        mass_action_worksheet: typing.Optional[MassActionWorksheet31485c9a93c0100007276cf4e5640000] = None,
        mass_action_header: typing.Optional[MassActionHeaderCf97466f96d910002bd32afbf0000001] = None,
        date: typing.Optional[date] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_change_event_mapped_args(
            body=body,
            position=position,
            mass_action_worksheet=mass_action_worksheet,
            mass_action_header=mass_action_header,
            date=date,
            id=id,
            descriptor=descriptor,
        )
        return await self._acreate_change_event_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        position: typing.Optional[PositionCf97466f96d9100029bffcf91c120001] = None,
        mass_action_worksheet: typing.Optional[MassActionWorksheet31485c9a93c0100007276cf4e5640000] = None,
        mass_action_header: typing.Optional[MassActionHeaderCf97466f96d910002bd32afbf0000001] = None,
        date: typing.Optional[date] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_change_event_mapped_args(
            body=body,
            position=position,
            mass_action_worksheet=mass_action_worksheet,
            mass_action_header=mass_action_header,
            date=date,
            id=id,
            descriptor=descriptor,
        )
        return self._create_change_event_oapg(
            body=args.body,
        )

