# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_staffing_python_sdk.type.business_process_parameters2dcd9a4882b210000f7b2e0a85982265 import BusinessProcessParameters2dcd9a4882b210000f7b2e0a85982265

BusinessProcessParameters5afc0b4b5a4610002aaebb8180cd2261 = typing.Union[BusinessProcessParameters2dcd9a4882b210000f7b2e0a85982265,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
