# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_staffing_python_sdk.type.assignment_type23929e1f68ca10000d6940d6bde56963 import AssignmentType23929e1f68ca10000d6940d6bde56963
from workday_staffing_python_sdk.type.change_job_company_insider_types_data05d4c45042b61000131e4b2132f30137 import ChangeJobCompanyInsiderTypesData05d4c45042b61000131e4b2132f30137
from workday_staffing_python_sdk.type.pay_rate_type_d25283821c01100016756a14eb650000 import PayRateTypeD25283821c01100016756a14eb650000
from workday_staffing_python_sdk.type.position_worker_type05d4c45042b610001030ee47f2c90118 import PositionWorkerType05d4c45042b610001030ee47f2c90118
from workday_staffing_python_sdk.type.time_type05d4c45042b610000bb540b7458e0108 import TimeType05d4c45042b610000bb540b7458e0108
from workday_staffing_python_sdk.type.work_study05d4c45042b610000ba2f83c70f30101 import WorkStudy05d4c45042b610000ba2f83c70f30101
from workday_staffing_python_sdk.type.workers_compensation_code_override05d4c45042b61000138500e185e0013f import WorkersCompensationCodeOverride05d4c45042b61000138500e185e0013f

ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800ea = typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
