# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_staffing_python_sdk.type.skill_item_d6ca778018011000182fa5f3b32001aa import SkillItemD6ca778018011000182fa5f3b32001aa
from workday_staffing_python_sdk.type.skill_source_representation998d2cc58f2f10000db59b08da0306a8 import SkillSourceRepresentation998d2cc58f2f10000db59b08da0306a8

DisplayExplicitSkillRepresentationD6ca778018011000182fa5be1ae901a8 = typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
