# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_staffing_python_sdk.type.change_job_administrative_details_data_f8f20079bc5a1000089ccb7f6a8800ea import ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800ea

class RequiredJobChangesGetAdministrativeOptionsResponse(TypedDict):
    pass

class OptionalJobChangesGetAdministrativeOptionsResponse(TypedDict, total=False):
    data: typing.List[ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800ea]

    total: int

class JobChangesGetAdministrativeOptionsResponse(RequiredJobChangesGetAdministrativeOptionsResponse, OptionalJobChangesGetAdministrativeOptionsResponse):
    pass
