# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_staffing_python_sdk.type.job_profile6fb921f8a11d10001d5268980bbb0097 import JobProfile6fb921f8a11d10001d5268980bbb0097
from workday_staffing_python_sdk.type.job_type_b8ac205877fd100005c55b45c6400057 import JobTypeB8ac205877fd100005c55b45c6400057
from workday_staffing_python_sdk.type.location6d3eb084b4c410002b617efb943f0059 import Location6d3eb084b4c410002b617efb943f0059
from workday_staffing_python_sdk.type.supervisory_organization_fab4a151b24810000d13073c5d341257 import SupervisoryOrganizationFab4a151b24810000d13073c5d341257
from workday_staffing_python_sdk.type.worker_fab4a151b24810000e66f769304c126b import WorkerFab4a151b24810000e66f769304c126b

JobData1bfa8925c50510000ae4479925510026 = typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
