# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_staffing_python_sdk.type.job75e528a78e9a10000ab7512c5c550115 import Job75e528a78e9a10000ab7512c5c550115
from workday_staffing_python_sdk.type.location75e528a78e9a10000ab75125ebe50114 import Location75e528a78e9a10000ab75125ebe50114
from workday_staffing_python_sdk.type.reason85deac43cd1a10000b96c80c118f171e import Reason85deac43cd1a10000b96c80c118f171e
from workday_staffing_python_sdk.type.supervisory_organization75e528a78e9a10000ab75132a9df0116 import SupervisoryOrganization75e528a78e9a10000ab75132a9df0116
from workday_staffing_python_sdk.type.template2b1b95dfe4af100007f63081aec5158e import Template2b1b95dfe4af100007f63081aec5158e

JobChangesStartDetailsPOSTData75e528a78e9a10000ab750ea156f0111 = typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
