# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_staffing_python_sdk.type.superior643e3a1262971000145238b2ccd10059 import Superior643e3a1262971000145238b2ccd10059
from workday_staffing_python_sdk.type.supervisory_organization_view_a02c2e1916fa100009e137235f1f0018 import SupervisoryOrganizationViewA02c2e1916fa100009e137235f1f0018

OrgChartView643e3a12629710000554e0338e670044 = typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
