# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.country_data_for_location_data_af21e47ff7c01000092e0e4f9a22026e import CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e
from workday_staffing_python_sdk import configuration


class TestCountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e(unittest.TestCase):
    """CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
