# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.pay_rate_type_related_view3b00708994e410000c52776049ba12c3 import PayRateTypeRelatedView3b00708994e410000c52776049ba12c3
from workday_staffing_python_sdk import configuration


class TestPayRateTypeRelatedView3b00708994e410000c52776049ba12c3(unittest.TestCase):
    """PayRateTypeRelatedView3b00708994e410000c52776049ba12c3 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
