# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.change_job_job_profile_data3db8095ffa18100013f019a27a1f0115 import ChangeJobJobProfileData3db8095ffa18100013f019a27a1f0115
from workday_staffing_python_sdk import configuration


class TestChangeJobJobProfileData3db8095ffa18100013f019a27a1f0115(unittest.TestCase):
    """ChangeJobJobProfileData3db8095ffa18100013f019a27a1f0115 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
