# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.company_insider_type_related_view7deab99f645f10001000f8a388740081 import CompanyInsiderTypeRelatedView7deab99f645f10001000f8a388740081
from workday_staffing_python_sdk import configuration


class TestCompanyInsiderTypeRelatedView7deab99f645f10001000f8a388740081(unittest.TestCase):
    """CompanyInsiderTypeRelatedView7deab99f645f10001000f8a388740081 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
