# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.worker_data_c2466b0778c610000d1936006720000e import WorkerDataC2466b0778c610000d1936006720000e
from workday_staffing_python_sdk import configuration


class TestWorkerDataC2466b0778c610000d1936006720000e(unittest.TestCase):
    """WorkerDataC2466b0778c610000d1936006720000e unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
