# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.associated_check_in_topic_detail316b5a26cc3c100010a01184c23902ea import AssociatedCheckInTopicDetail316b5a26cc3c100010a01184c23902ea
from workday_staffing_python_sdk import configuration


class TestAssociatedCheckInTopicDetail316b5a26cc3c100010a01184c23902ea(unittest.TestCase):
    """AssociatedCheckInTopicDetail316b5a26cc3c100010a01184c23902ea unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
