# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.country3b00708994e4100004edeb4e0d37128c import Country3b00708994e4100004edeb4e0d37128c
from workday_staffing_python_sdk import configuration


class TestCountry3b00708994e4100004edeb4e0d37128c(unittest.TestCase):
    """Country3b00708994e4100004edeb4e0d37128c unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
