# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.job_profile_b8ac205877fd10000ea9174f73c500aa import JobProfileB8ac205877fd10000ea9174f73c500aa
from workday_staffing_python_sdk import configuration


class TestJobProfileB8ac205877fd10000ea9174f73c500aa(unittest.TestCase):
    """JobProfileB8ac205877fd10000ea9174f73c500aa unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
