# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.country_or_region_related_view3b00708994e4100007e9c8f14e3812ae import CountryOrRegionRelatedView3b00708994e4100007e9c8f14e3812ae
from workday_staffing_python_sdk import configuration


class TestCountryOrRegionRelatedView3b00708994e4100007e9c8f14e3812ae(unittest.TestCase):
    """CountryOrRegionRelatedView3b00708994e4100007e9c8f14e3812ae unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
