# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.check_in_topic_attachment_detail600ecde4c8421000278d06bfacea01c1 import CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1
from workday_staffing_python_sdk import configuration


class TestCheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1(unittest.TestCase):
    """CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
