# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.supervisory_organization_job_view_fab4a151b24810000d29746fb7e21259 import SupervisoryOrganizationJobViewFab4a151b24810000d29746fb7e21259
from workday_staffing_python_sdk import configuration


class TestSupervisoryOrganizationJobViewFab4a151b24810000d29746fb7e21259(unittest.TestCase):
    """SupervisoryOrganizationJobViewFab4a151b24810000d29746fb7e21259 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
