# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.check_in_topics_summary_d81c816de26f10000ef2c5cb2fdd0015 import CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015
from workday_staffing_python_sdk import configuration


class TestCheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015(unittest.TestCase):
    """CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
