# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.skill_item_display_definition4b4b7d34b4a21000301eaf52086700d8 import SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8
from workday_staffing_python_sdk import configuration


class TestSkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8(unittest.TestCase):
    """SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
