# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.template2b1b95dfe4af100007f63081aec5158e import Template2b1b95dfe4af100007f63081aec5158e
from workday_staffing_python_sdk import configuration


class TestTemplate2b1b95dfe4af100007f63081aec5158e(unittest.TestCase):
    """Template2b1b95dfe4af100007f63081aec5158e unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
