# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

import unittest

import workday_staffing_python_sdk
from workday_staffing_python_sdk.model.job_changes_start_details_data_ce861a6a360d10002d40f176b7180020 import JobChangesStartDetailsDataCe861a6a360d10002d40f176b7180020
from workday_staffing_python_sdk import configuration


class TestJobChangesStartDetailsDataCe861a6a360d10002d40f176b7180020(unittest.TestCase):
    """JobChangesStartDetailsDataCe861a6a360d10002d40f176b7180020 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
