# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from workday_staffing_python_sdk import schemas  # noqa: F401


class CreateSkillUsageRepresentation98f198f5056b1000196313ffe9a0225e(
    schemas.ComposedSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        
        class all_of_0(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    
                    
                    class skills(
                        schemas.ListSchema
                    ):
                    
                    
                        class MetaOapg:
                            
                            @staticmethod
                            def items() -> typing.Type['DisplayExplicitSkillRepresentationD6ca778018011000182fa5be1ae901a8']:
                                return DisplayExplicitSkillRepresentationD6ca778018011000182fa5be1ae901a8
                    
                        def __new__(
                            cls,
                            arg: typing.Union[typing.Tuple['DisplayExplicitSkillRepresentationD6ca778018011000182fa5be1ae901a8'], typing.List['DisplayExplicitSkillRepresentationD6ca778018011000182fa5be1ae901a8']],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                        ) -> 'skills':
                            return super().__new__(
                                cls,
                                arg,
                                _configuration=_configuration,
                            )
                    
                        def __getitem__(self, i: int) -> 'DisplayExplicitSkillRepresentationD6ca778018011000182fa5be1ae901a8':
                            return super().__getitem__(i)
                
                    @staticmethod
                    def skillItem() -> typing.Type['SkillItem98f198f5056b100019631445471d225f']:
                        return SkillItem98f198f5056b100019631445471d225f
                    
                    
                    class skillSources(
                        schemas.ListSchema
                    ):
                    
                    
                        class MetaOapg:
                            
                            @staticmethod
                            def items() -> typing.Type['SkillItemSourceAddRepresentationC5fabc4ca81610000d5d15309ac90122']:
                                return SkillItemSourceAddRepresentationC5fabc4ca81610000d5d15309ac90122
                    
                        def __new__(
                            cls,
                            arg: typing.Union[typing.Tuple['SkillItemSourceAddRepresentationC5fabc4ca81610000d5d15309ac90122'], typing.List['SkillItemSourceAddRepresentationC5fabc4ca81610000d5d15309ac90122']],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                        ) -> 'skillSources':
                            return super().__new__(
                                cls,
                                arg,
                                _configuration=_configuration,
                            )
                    
                        def __getitem__(self, i: int) -> 'SkillItemSourceAddRepresentationC5fabc4ca81610000d5d15309ac90122':
                            return super().__getitem__(i)
                    __annotations__ = {
                        "skills": skills,
                        "skillItem": skillItem,
                        "skillSources": skillSources,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["skills"]) -> MetaOapg.properties.skills: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["skillItem"]) -> 'SkillItem98f198f5056b100019631445471d225f': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["skillSources"]) -> MetaOapg.properties.skillSources: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["skills", "skillItem", "skillSources", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["skills"]) -> typing.Union[MetaOapg.properties.skills, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["skillItem"]) -> typing.Union['SkillItem98f198f5056b100019631445471d225f', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["skillSources"]) -> typing.Union[MetaOapg.properties.skillSources, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["skills", "skillItem", "skillSources", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *args: typing.Union[dict, frozendict.frozendict, ],
                skills: typing.Union[MetaOapg.properties.skills, list, tuple, schemas.Unset] = schemas.unset,
                skillItem: typing.Union['SkillItem98f198f5056b100019631445471d225f', schemas.Unset] = schemas.unset,
                skillSources: typing.Union[MetaOapg.properties.skillSources, list, tuple, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_0':
                return super().__new__(
                    cls,
                    *args,
                    skills=skills,
                    skillItem=skillItem,
                    skillSources=skillSources,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                cls.all_of_0,
            ]


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CreateSkillUsageRepresentation98f198f5056b1000196313ffe9a0225e':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )

from workday_staffing_python_sdk.model.display_explicit_skill_representation_d6ca778018011000182fa5be1ae901a8 import DisplayExplicitSkillRepresentationD6ca778018011000182fa5be1ae901a8
from workday_staffing_python_sdk.model.skill_item98f198f5056b100019631445471d225f import SkillItem98f198f5056b100019631445471d225f
from workday_staffing_python_sdk.model.skill_item_source_add_representation_c5fabc4ca81610000d5d15309ac90122 import SkillItemSourceAddRepresentationC5fabc4ca81610000d5d15309ac90122
