# coding: utf-8

"""
    staffing

    The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes

    The version of the OpenAPI document: v6
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from workday_staffing_python_sdk import schemas  # noqa: F401


class JobProfilePayRateTypeRelatedView3b00708994e4100008d4b09e903f12b5(
    schemas.ComposedSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        
        class all_of_0(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                
                    @staticmethod
                    def payRateType() -> typing.Type['PayRateType3b00708994e410000c3d01aea96012c1']:
                        return PayRateType3b00708994e410000c3d01aea96012c1
                
                    @staticmethod
                    def country() -> typing.Type['Country3b00708994e41000095e4647007012bc']:
                        return Country3b00708994e41000095e4647007012bc
                    __annotations__ = {
                        "payRateType": payRateType,
                        "country": country,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["payRateType"]) -> 'PayRateType3b00708994e410000c3d01aea96012c1': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["country"]) -> 'Country3b00708994e41000095e4647007012bc': ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["payRateType", "country", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["payRateType"]) -> typing.Union['PayRateType3b00708994e410000c3d01aea96012c1', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["country"]) -> typing.Union['Country3b00708994e41000095e4647007012bc', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["payRateType", "country", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *args: typing.Union[dict, frozendict.frozendict, ],
                payRateType: typing.Union['PayRateType3b00708994e410000c3d01aea96012c1', schemas.Unset] = schemas.unset,
                country: typing.Union['Country3b00708994e41000095e4647007012bc', schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_0':
                return super().__new__(
                    cls,
                    *args,
                    payRateType=payRateType,
                    country=country,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                cls.all_of_0,
            ]


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'JobProfilePayRateTypeRelatedView3b00708994e4100008d4b09e903f12b5':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )

from workday_staffing_python_sdk.model.country3b00708994e41000095e4647007012bc import Country3b00708994e41000095e4647007012bc
from workday_staffing_python_sdk.model.pay_rate_type3b00708994e410000c3d01aea96012c1 import PayRateType3b00708994e410000c3d01aea96012c1
